import { makeStyles } from '@mui/styles';

export default makeStyles(() => ({
  container: {
    backgroundColor: '#121212',
    width: '100%',
    paddingLeft: '30px',
    paddingTop: '10px',
  },
  tracks: {
    display: 'flex',
    flexDirection: 'column',
    color: 'white',
    width: 'auto',
  },
  search: {
    height: '35px',
    width: '365px',
    borderRadius: '500px',
    outline: 'none',
    letterSpacing: 'normal',
    fontSize: '1em',
  },
  fragmentTitle: {
    color: 'white',
    fontSize: '1.5em',
    marginBottom: '20px',
    fontFamily: 'CircularBold',
  },
  topResult: {
    color: 'white',
    cursor: 'pointer',
    width: '415px',
    height: '195px',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    paddingLeft: '20px',
    paddingTop: '20px',
    backgroundColor: '#181818',
    fontFamily: 'CircularBold',
    '&:hover': { backgroundColor: '#242424', transitionDuration: '0.2s' },
  },
  artistHeroMain: {
    height: '95px',
    width: '95px',
    borderRadius: '50%',
    boxShadow: '0 0 10px 3px #181818',
  },
  artistHeroSub: {
    height: '170px',
    width: '170px',
    borderRadius: '50%',
    boxShadow: '0 0 10px 3px #181818',
  },
  displayText: {
    color: 'white',
    fontSize: '2em',
    fontFamily: 'CircularBold',
  },
  song: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '10px',
    paddingLeft: '10px',
    height: '56px',
    fontSize: '1em',
    fontFamily: 'CircularCyr',
    cursor: 'pointer',
    '&:hover': { backgroundColor: '#242424', transitionDuration: '0.2s' },
  },
  song2: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '95%',
    alignItems: 'center',
    borderRadius: '10px',
    '&:hover': { backgroundColor: '#242424', transitionDuration: '0.2s' },
  },
  artist: {
    padding: '17px',
    color: 'white',
    backgroundColor: '#181818',
    borderRadius: '10px',
    maxWidth: '200px',
    fontFamily: 'CircularBold',
    cursor: 'pointer',
    '&:hover': { backgroundColor: '#242424', transitionDuration: '0.2s' },
  },
}));

//mouseover #242424
